name: meuplanoai

services:
  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/meuplanoai
    env_file:
      - ./backend/.env.development

  backend-test:
    container_name: backend-test
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    env_file:
      - ./backend/.env.development

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # Banco de dados MongoDB (desenvolvimento)
  mongodb:
    container_name: mongodb
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: meuplanoai

  # Serviço do frontend (desenvolvimento)
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules                     # Evita apagar node_modules do container
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"   # variável a partir de ./.env (host:container)
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}        # porta usada pelo Vite dentro do container
    env_file:
      - ./frontend/.env.development           # injeta VITE_API_URL no ambiente

  frontend-test:
    container_name: frontend-test
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: test
    env_file:
      - ./frontend/.env.development           # injeta variaveis dentro do ambiente

volumes:
  ollama_data:
  mongodb_data: 